IF EXISTS (SELECT * FROM sys.objects WHERE  name = 'REMOVE_LAST_SIMBOL')
DROP FUNCTION [dbo].[REMOVE_LAST_SIMBOL]
GO
CREATE FUNCTION [dbo].[REMOVE_LAST_SIMBOL] (@str nvarchar(MAX))
RETURNS nvarchar(MAX)
AS
BEGIN
	RETURN LEFT(@str, LEN(@str)-1);
END
GO

