//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Modules.Localize.Game.Units {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Modules.Localize.Game.Units.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attack.
        /// </summary>
        public static string AttackName {
            get {
                return ResourceManager.GetString("AttackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battlecruiser is....
        /// </summary>
        public static string BattleCruiserDescription {
            get {
                return ResourceManager.GetString("BattleCruiserDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Battlecruiser.
        /// </summary>
        public static string BattleCruiserName {
            get {
                return ResourceManager.GetString("BattleCruiserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BattleShip is....
        /// </summary>
        public static string BattleShipDescription {
            get {
                return ResourceManager.GetString("BattleShipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на BattleShip.
        /// </summary>
        public static string BattleShipName {
            get {
                return ResourceManager.GetString("BattleShipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confederation Credits.
        /// </summary>
        public static string Cc {
            get {
                return ResourceManager.GetString("Cc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Command сenter.
        /// </summary>
        public static string CommandCenter {
            get {
                return ResourceManager.GetString("CommandCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CurrentValue en.
        /// </summary>
        public static string CurrentValue {
            get {
                return ResourceManager.GetString("CurrentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dark matter.
        /// </summary>
        public static string DarkMatter {
            get {
                return ResourceManager.GetString("DarkMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drednout is....
        /// </summary>
        public static string DrednoutDescription {
            get {
                return ResourceManager.GetString("DrednoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drednout.
        /// </summary>
        public static string DrednoutName {
            get {
                return ResourceManager.GetString("DrednoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drone is....
        /// </summary>
        public static string DroneDescription {
            get {
                return ResourceManager.GetString("DroneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Drone.
        /// </summary>
        public static string DroneName {
            get {
                return ResourceManager.GetString("DroneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enegry.
        /// </summary>
        public static string Enegry {
            get {
                return ResourceManager.GetString("Enegry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange.
        /// </summary>
        public static string EnergyConverter {
            get {
                return ResourceManager.GetString("EnergyConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на EnergyConverterDescripton en.
        /// </summary>
        public static string EnergyConverterDescripton {
            get {
                return ResourceManager.GetString("EnergyConverterDescripton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange course.
        /// </summary>
        public static string ExchangeCourse {
            get {
                return ResourceManager.GetString("ExchangeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extraction.
        /// </summary>
        public static string ExtractionModule {
            get {
                return ResourceManager.GetString("ExtractionModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ExtractionModuleDescription en.
        /// </summary>
        public static string ExtractionModuleDescription {
            get {
                return ResourceManager.GetString("ExtractionModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frigate is....
        /// </summary>
        public static string FrigateDescription {
            get {
                return ResourceManager.GetString("FrigateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Frigate.
        /// </summary>
        public static string FrigateName {
            get {
                return ResourceManager.GetString("FrigateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HangarToggle.
        /// </summary>
        public static string HangarToggle {
            get {
                return ResourceManager.GetString("HangarToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Structure.
        /// </summary>
        public static string HpName {
            get {
                return ResourceManager.GetString("HpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Industrial сomplex.
        /// </summary>
        public static string IndustrialComplex {
            get {
                return ResourceManager.GetString("IndustrialComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Iroxium.
        /// </summary>
        public static string Iridium {
            get {
                return ResourceManager.GetString("Iridium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MaxStorableDarkMatter en.
        /// </summary>
        public static string MaxStorableDarkMatter {
            get {
                return ResourceManager.GetString("MaxStorableDarkMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MaxStorableEnegy en.
        /// </summary>
        public static string MaxStorableEnegy {
            get {
                return ResourceManager.GetString("MaxStorableEnegy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MaxStorableIroxium en.
        /// </summary>
        public static string MaxStorableIridium {
            get {
                return ResourceManager.GetString("MaxStorableIridium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exchange.
        /// </summary>
        public static string MotherEnergyConverter {
            get {
                return ResourceManager.GetString("MotherEnergyConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MotherEnergyConverterDescription en.
        /// </summary>
        public static string MotherEnergyConverterDescription {
            get {
                return ResourceManager.GetString("MotherEnergyConverterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extraction.
        /// </summary>
        public static string MotherExtractionModule {
            get {
                return ResourceManager.GetString("MotherExtractionModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MotherExtractionModuleDescription en.
        /// </summary>
        public static string MotherExtractionModuleDescription {
            get {
                return ResourceManager.GetString("MotherExtractionModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Industrial Complex.
        /// </summary>
        public static string MotherIndustrialComplex {
            get {
                return ResourceManager.GetString("MotherIndustrialComplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Space Shipyard.
        /// </summary>
        public static string MotherSpaceShipyard {
            get {
                return ResourceManager.GetString("MotherSpaceShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MotherSpaceShipyardDescription en.
        /// </summary>
        public static string MotherSpaceShipyardDescription {
            get {
                return ResourceManager.GetString("MotherSpaceShipyardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string MotherStorage {
            get {
                return ResourceManager.GetString("MotherStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MotherStorageDescription en.
        /// </summary>
        public static string MotherStorageDescription {
            get {
                return ResourceManager.GetString("MotherStorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NextValue en.
        /// </summary>
        public static string NextValue {
            get {
                return ResourceManager.GetString("NextValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Power.
        /// </summary>
        public static string ProductionPower {
            get {
                return ResourceManager.GetString("ProductionPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select target.
        /// </summary>
        public static string SelectTarget {
            get {
                return ResourceManager.GetString("SelectTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send all.
        /// </summary>
        public static string SendAll {
            get {
                return ResourceManager.GetString("SendAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Space shipyard.
        /// </summary>
        public static string SpaceShipyard {
            get {
                return ResourceManager.GetString("SpaceShipyard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SpaceShipyardDescription en.
        /// </summary>
        public static string SpaceShipyardDescription {
            get {
                return ResourceManager.GetString("SpaceShipyardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Storage.
        /// </summary>
        public static string Storage {
            get {
                return ResourceManager.GetString("Storage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StorageDescriptionEn       Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida mi sit amet nisl pharetra, vitae ultricies sem laoreet. Ut at suscipit mi. Duis enim nunc, placerat sit amet mauris sit amet, hendrerit pulvinar felis. Curabitur pharetra venenatis ipsum eget posuere. Suspendisse mauris dui, iaculis vitae posuere et, iaculis et dolor. Ut finibus maximus ultrices. Suspendisse fermentum pharetra pulvinar. In auctor augue magna, id tempus lorem pellentesque non. Cras aliquam congu [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string StorageDescription {
            get {
                return ResourceManager.GetString("StorageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time production.
        /// </summary>
        public static string TimeProduction {
            get {
                return ResourceManager.GetString("TimeProduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TransferLosses en.
        /// </summary>
        public static string TransferLosses {
            get {
                return ResourceManager.GetString("TransferLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turel en.
        /// </summary>
        public static string Turel {
            get {
                return ResourceManager.GetString("Turel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Turel Description en.
        /// </summary>
        public static string TurelDescription {
            get {
                return ResourceManager.GetString("TurelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
    }
}
