//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Modules.Localize.Site.Home {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Server.Modules.Localize.Site.Home.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An open world with thousands of solar systems. You can do whatever you want. Explore the universe, colonize planets, mine resources, build armys, improve technologies, fight for sovereignty and reign over the universe together with thousands of other players..
        /// </summary>
        public static string f_freedomOfActionBody {
            get {
                return ResourceManager.GetString("f_freedomOfActionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sandbox.
        /// </summary>
        public static string f_freedomOfActionHead {
            get {
                return ResourceManager.GetString("f_freedomOfActionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A unique feature of the game is that each player can become the leader of the human race in the fight against Skagry and gain a significant advantage in the development and military power for himself and all of his supporters..
        /// </summary>
        public static string f_presidentElectionsBody {
            get {
                return ResourceManager.GetString("f_presidentElectionsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Government Elections.
        /// </summary>
        public static string f_presidentElectionsHead {
            get {
                return ResourceManager.GetString("f_presidentElectionsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You will be able to attack any player, regardless of his development level and the size of his army. Anytime and anywhere. As a reward for defeating other players, you will earn PVP points needed to advance in the ranking and secure the Presidency of the Confederation..
        /// </summary>
        public static string f_systemPvpNolimitsBody {
            get {
                return ResourceManager.GetString("f_systemPvpNolimitsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hardcore PvP.
        /// </summary>
        public static string f_systemPvpNolimitsHead {
            get {
                return ResourceManager.GetString("f_systemPvpNolimitsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The game has no restrictions on the level of development of colonies and technologies. You can upgrade any building or technology to the level you want. This will allow you to plan your development in greater detail and focus on the aspect of the game you are interested in most..
        /// </summary>
        public static string f_systemUpgradeNoLimitsBody {
            get {
                return ResourceManager.GetString("f_systemUpgradeNoLimitsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No level restrictions.
        /// </summary>
        public static string f_systemUpgradeNoLimitsHead {
            get {
                return ResourceManager.GetString("f_systemUpgradeNoLimitsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Features.
        /// </summary>
        public static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create a powerful alliance capable of conquering the universe or join one. Colonize planets and defend them from the attacks of Skagry and other players. Remember, sovereignty is the key to dominance over the universe..
        /// </summary>
        public static string g_alliance {
            get {
                return ResourceManager.GetString("g_alliance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alliance and sovereignty.
        /// </summary>
        public static string g_allianceHead {
            get {
                return ResourceManager.GetString("g_allianceHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are the Commander of the Confederation Fleet. You have your own mothership that you will never lose. You are not bound to any location, and can move freely across the universe with thousands of solar systems and with multiple planets available for colonization and development. After securing enough colonies, you will become a prominent figure in the Confederation and will be able to establish a powerful empire under your command to influence the course of events in the universe. Of course, it will be ha [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string g_gamePlay {
            get {
                return ResourceManager.GetString("g_gamePlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Gameplay.
        /// </summary>
        public static string g_gamePlayHead {
            get {
                return ResourceManager.GetString("g_gamePlayHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Become President of the Confederation with the most votes in weekly elections or support the candidate you like. Win the trust of voters or find another almost legal way to win elections..
        /// </summary>
        public static string g_Politics {
            get {
                return ResourceManager.GetString("g_Politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Politics and Diplomacy.
        /// </summary>
        public static string g_PoliticsHead {
            get {
                return ResourceManager.GetString("g_PoliticsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Build troops at your colonial bases, increase the combat ability of your army or step up defence of your colonies, turning them into impenetrable fortresses. Choose your unique path for the development of technologies to conquer the universe..
        /// </summary>
        public static string g_Production {
            get {
                return ResourceManager.GetString("g_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Production and Technology.
        /// </summary>
        public static string g_ProductionHead {
            get {
                return ResourceManager.GetString("g_ProductionHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Each region has its own features and different concentrations of Skagry. Each solar system is unique, and you will never find two identical solar systems. Planets also differ in terms of available resources and the benefits of ownership..
        /// </summary>
        public static string g_Regions {
            get {
                return ResourceManager.GetString("g_Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regions and solar system.
        /// </summary>
        public static string g_RegionsHead {
            get {
                return ResourceManager.GetString("g_RegionsHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confederation.
        /// </summary>
        public static string r_Confederation {
            get {
                return ResourceManager.GetString("r_Confederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на United forces of humanity in the fight against Skagry. A single government headed by the President and Ministers. The President and five Ministers are elected by the people, and the other five are appointed by the President. The Confederation’s symbol displays its structure. The President is denoted by a big star in the middle. The stars on the left-hand side represent the Ministers elected by the people, who often do not share the President’s views and go into opposition. The stars on the right-hand side s [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string r_ConfederationDescription {
            get {
                return ResourceManager.GetString("r_ConfederationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Skagry - NPC.
        /// </summary>
        public static string r_RaceSkagry {
            get {
                return ResourceManager.GetString("r_RaceSkagry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Alien species with an accelerated regeneration and reproductive function. Obey the collective wisdom and act on the principle of Roy, the aim of which is to absorb all life forms encountered on the way, and the creation of colonies in all possible areas. Skagry instantly adapt to the weather conditions and landshavtnym any planet that always allows them to fight at home, greatly complicating the task at the same time for the Confederate forces. Skagry ruthless and do not know fear. Without exaggeration, thi [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string r_RaceSkagryDescription {
            get {
                return ResourceManager.GetString("r_RaceSkagryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Screenshots.
        /// </summary>
        public static string screenshots {
            get {
                return ResourceManager.GetString("screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на story.
        /// </summary>
        public static string story {
            get {
                return ResourceManager.GetString("story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на In the future, when space has long ceased to be a mystery for humans and conquering new worlds became commonplace, humans discovered creatures with an incredible ability to regenerate, called Skagry. Later, their genome was discovered to contain information that gave people eternal life. However, humans found that to be insufficient and began breeding Skagry and experiment with their genes. At some point the situation got out of control and Skagry broke free. Driven by a collective mind, they overtook plane [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string storyDescription {
            get {
                return ResourceManager.GetString("storyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Game.
        /// </summary>
        public static string theGame {
            get {
                return ResourceManager.GetString("theGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Universe.
        /// </summary>
        public static string TheUniverse {
            get {
                return ResourceManager.GetString("TheUniverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на skagry_trailer_en.
        /// </summary>
        public static string VideoUniverseOfSkagryTrailer {
            get {
                return ResourceManager.GetString("VideoUniverseOfSkagryTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на jlsde2lxO68.
        /// </summary>
        public static string YoutubeVideoUniverseOfSkagryTrailer {
            get {
                return ResourceManager.GetString("YoutubeVideoUniverseOfSkagryTrailer", resourceCulture);
            }
        }
    }
}
